services:
  - type: web
    name: no-locals-frontend
    buildCommand: npm run build --prefix client
    startCommand: npm run preview --prefix client
    routes:
      - path: /*
        destination: /index.html
