services:
  - type: web
    name: no-locals-frontend
    buildCommand: rm -rf node_modules package-lock.json client/node_modules server/node_modules && npm install --include=optional && npm run client:build
    startCommand: npx serve -s client/dist -l $PORT
    routes:
      - path: /*
        destination: /index.html
