name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: no_locals_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: 22.x 
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install all dependencies
        run: npm install

      # --- LINTING ---
      - name: Lint Client
        run: npm run lint -w client
      
      - name: Lint Server
        run: npm run lint -w server

      # --- BUILD STEP ---
      # builds the client's static files.
      - name: Build Client
        run: npm run build -w client

      # --- TESTING ---
      - name: Run Server Tests
        # The server tests run after the client has been built.
        run: npm test -w server
        env:
          # This connects to the PostgreSQL service container running in the job.
          DATABASE_URL: postgres://postgres:password@localhost:5432/no_locals_test
          JWT_SECRET: super_secret_test_key
          NODE_ENV: test
       
          IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
          IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
          IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}

      - name: Run Client Tests
        run: npm test -w client